# Generated by Django 4.2.13 on 2026-05-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('gen_ai', 'Generative AI'), ('machine_learning', 'Machine Learning'), ('nlp', 'NLP'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('flutter', 'Flutter'), ('data_science', 'Data Science'), ('data_analytics', 'Data Analytics'), ('devops', 'DevOps')], default='backend', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='stack',
            field=models.CharField(choices=[('general', 'General'), ('django', 'Django'), ('nodejs', 'Node.js'), ('react', 'React'), ('vue', 'Vue.js'), ('flutter', 'Flutter'), ('python', 'Python')], default='general', help_text='Tech stack track (e.g. Django vs Node.js for backend)', max_length=20),
        ),
    ]
