# Generated by Django 4.2.13 on 2026-05-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_category_course_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=29.99, help_text='Course enrollment price in USD', max_digits=8),
        ),
        migrations.AddField(
            model_name='course',
            name='student_count',
            field=models.PositiveIntegerField(default=0, help_text='Baseline enrolled student count'),
        ),
    ]
